spring.application.name=helpdesk

# === Database ===
spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:test123}

# === JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Africa/Tunis
spring.jackson.time-zone=Africa/Tunis

# === Security ===
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# === JWT ===
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=604800000

# === SMTP OVH ===
app.smtp.host=ssl0.ovh.net
app.smtp.port=587
app.smtp.user=${SMTP_USER}
app.smtp.password=${SMTP_PASSWORD}
app.smtp.from-email=${SMTP_USER}
app.smtp.from-name=HelpDesk IT

# === SMTP (configuré dynamiquement via SmtpConfigService, non utilisé directement) ===
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=${GMAIL_USER}
# spring.mail.password=${GMAIL_APP_PASSWORD}
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

# === Groq AI ===
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant

# === Admin ===
admin.email=${SMTP_USER}

# === Server ===
server.port=8080
logging.level.com.helpdesk.service.EmailService=DEBUG
logging.level.com.helpdesk.service.SmtpConfigService=DEBUG
mail.debug=true

frontend_base_url=http://localhost:5173